#ifndef DETECTORLIB_GLOBAL_H
#define DETECTORLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DETECTORLIB_LIBRARY)
#  define DETECTORLIB_EXPORT Q_DECL_EXPORT
#else
#  define DETECTORLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // DETECTORLIB_GLOBAL_H
